language: node_js
node_js:
- '6'
- '8'
- '9'
- '10'
- '11'
- '12'
before_script:
- npm install
deploy:
  provider: npm
  email: dirkx@apache.org
  api_key:
    secure: <hidden>
  on:
    tags: true
    branch: master
    repo: dirkx/base45

